services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
    command: >
      uv run gunicorn -k uvicorn.workers.UvicornWorker
      --workers 2
      --bind 0.0.0.0:8000
      app.main:app

  poller:
    build: .
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - TICKERS=CL=F,BZ=F,GC=F,SI=F,NG=F,HO=F,RB=F,XOM,CVX,COP,OXY,EOG,KMI,PSX,VLO,USO
      - POLL_FREQ=3600
      - REDIS_URL=redis://redis:6379
    command: >
      uv run python -m app.polling_worker
