name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml','**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Lint and test
        run: |
          make ci

  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build API Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file:    packages/api/Dockerfile
          push:    false
          tags:    fastapi-ticker-hub-api:ci

      - name: Build Poller Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file:    packages/poller/Dockerfile
          push:    false
          tags:    fastapi-ticker-hub-poller:ci

      - name: Verify API image exists
        run: docker image inspect fastapi-ticker-hub-api:ci

      - name: Verify Poller image exists
        run: docker image inspect fastapi-ticker-hub-poller:ci